Repository social-bookmark-9/backend, pull requests merged in 2022-04, with the labels that each got.

#196 feat: contentOg 50자 제한 적용
  build.gradle
  src/main/java/com/sparta/backend/serviceImpl/ArticleServiceImpl.java
  src/main/java/com/sparta/backend/utils/JsoupParser.java
Labels: 🚀 기능추가

#197 refactor: 검색페이지 기능 추가
  src/main/java/com/sparta/backend/controller/SearchPageControllerTest.java
  src/main/java/com/sparta/backend/model/Member.java
  src/main/java/com/sparta/backend/repository/ArticleRepository.java
  src/main/java/com/sparta/backend/repository/MemberRepository.java
  src/main/java/com/sparta/backend/service/SearchPageServiceTest.java
  src/main/java/com/sparta/backend/serviceImpl/OauthServiceImpl.java
  src/main/java/com/sparta/backend/serviceImpl/SearchPageServiceTestImpl.java
  src/test/java/com/sparta/backend/nplus1/nplus1test.java
Labels: 🚀 기능추가, 🛠 리팩토링

#198 refactor: 아티클 폴더 수정 및 기타 코드 수정, Querydsl 의존성 주입
  build.gradle
  src/main/java/com/sparta/backend/controller/ArticleFolderController.java
  src/main/java/com/sparta/backend/controller/MyPageController.java
  src/main/java/com/sparta/backend/model/Article.java
  src/main/java/com/sparta/backend/model/ArticleFolder.java
  src/main/java/com/sparta/backend/model/Member.java
  src/main/java/com/sparta/backend/repository/ArticleFolderRepository.java
  src/main/java/com/sparta/backend/repository/ArticleFolderRepositoryCustom.java
  src/main/java/com/sparta/backend/repository/ArticleFolderRepositoryImpl.java
  src/main/java/com/sparta/backend/repository/FavoriteRepository.java
  src/main/java/com/sparta/backend/repository/MemberRepository.java
  src/main/java/com/sparta/backend/responseDto/ArticleFolderListResponseDto.java
  src/main/java/com/sparta/backend/service/ArticleFolderService.java
  src/main/java/com/sparta/backend/service/MyPageService.java
  src/main/java/com/sparta/backend/serviceImpl/ArticleFolderServiceImpl.java
  src/main/java/com/sparta/backend/serviceImpl/ArticleServiceImpl.java
  src/main/java/com/sparta/backend/serviceImpl/MyPageServiceImpl.java
  src/main/java/com/sparta/backend/utils/DummyData.java
  src/test/java/com/sparta/backend/nplus1/nplus1test.java
  src/test/java/com/sparta/backend/repository/FavoriteRepositoryTest.java
  src/test/java/com/sparta/backend/serviceImpl/ArticleFolderServiceTest.java
  src/test/java/com/sparta/backend/serviceImpl/MyPageServiceImplTest.java
  src/test/java/com/sparta/backend/serviceImpl/ReminderServiceTest.java
Labels: 🗂 의존성설치, 🛠 리팩토링

#200 bug: 리마인드 삭제 영속성 문제 및 로그인 리팩토링
  src/main/java/com/sparta/backend/controller/OauthController.java
  src/main/java/com/sparta/backend/controller/SearchPageControllerTest.java
  src/main/java/com/sparta/backend/model/ArticleFolder.java
  src/main/java/com/sparta/backend/repository/ArticleFolderRepository.java
  src/main/java/com/sparta/backend/repository/ArticleFolderRepositoryCustom.java
  src/main/java/com/sparta/backend/repository/ArticleFolderRepositoryImpl.java
  src/main/java/com/sparta/backend/repository/ReminderRepository.java
  src/main/java/com/sparta/backend/repositorycustom/ArticleFolderRepositoryCustom.java
  src/main/java/com/sparta/backend/repositorycustom/ArticleFolderRepositoryImpl.java
  src/main/java/com/sparta/backend/service/OauthService.java
  src/main/java/com/sparta/backend/service/SearchPageServiceTest.java
  src/main/java/com/sparta/backend/serviceImpl/MainPageServiceImpl.java
  src/main/java/com/sparta/backend/serviceImpl/OauthServiceImpl.java
  src/main/java/com/sparta/backend/serviceImpl/ReminderServiceImpl.java
  src/main/java/com/sparta/backend/serviceImpl/SearchPageServiceTestImpl.java
  src/main/java/com/sparta/backend/utils/DummyData.java
  src/main/java/com/sparta/backend/utils/TestMailController.java
  src/main/resources/templates/newEmail.html
  src/test/java/com/sparta/backend/serviceImpl/ReminderServiceTest.java
Labels: 🐞 버그, 🛠 리팩토링

#203 refactor: 검색페이지 디코딩
  src/main/java/com/sparta/backend/controller/SearchPageControllerTest.java
  src/main/java/com/sparta/backend/requestDto/ArticleFolderCreateRequestDto.java
Labels: 🛠 리팩토링

#207 refactor : 메인페이지 아티클 추천 및 검색페이지 param 디코딩 방식 수정
  src/main/java/com/sparta/backend/controller/MainPageArticleController.java
  src/main/java/com/sparta/backend/controller/SearchPageControllerTest.java
Labels: 🛠 리팩토링

#208 refactor : 메인페이지 아티클 추천 및 검색페이지 param 디코딩 방식 수정
  src/main/java/com/sparta/backend/controller/MainPageArticleController.java
  src/main/java/com/sparta/backend/controller/SearchPageControllerTest.java
Labels: 🥊 배포

#213 refactor: 검색페이지 아티클 최적화
  src/main/java/com/sparta/backend/jwt/JwtTokenProvider.java
  src/main/java/com/sparta/backend/repository/ArticleRepository.java
  src/main/java/com/sparta/backend/responseDto/SearchPageArticleResponseDto.java
  src/main/java/com/sparta/backend/security/WebConfig.java
  src/main/java/com/sparta/backend/serviceImpl/OauthServiceImpl.java
  src/main/java/com/sparta/backend/serviceImpl/SearchPageServiceTestImpl.java
  src/main/java/com/sparta/backend/utils/DummyData.java
Labels: 🛠 리팩토링

#214 refactor, hotfix: 검색페이지 아티클 최적화, 카카오 redirect uri 변경
  src/main/java/com/sparta/backend/jwt/JwtTokenProvider.java
  src/main/java/com/sparta/backend/repository/ArticleRepository.java
  src/main/java/com/sparta/backend/responseDto/SearchPageArticleResponseDto.java
  src/main/java/com/sparta/backend/security/WebConfig.java
  src/main/java/com/sparta/backend/serviceImpl/OauthServiceImpl.java
  src/main/java/com/sparta/backend/serviceImpl/SearchPageServiceTestImpl.java
  src/main/java/com/sparta/backend/utils/DummyData.java
Labels: 🛠 리팩토링, ❗️ 긴급

#215 refactor: 이메일 수정
  readme.md
  src/main/java/com/sparta/backend/controller/MemberInfoController.java
  src/main/java/com/sparta/backend/serviceImpl/OauthServiceImpl.java
  src/main/java/com/sparta/backend/utils/EmailScheduler.java
  src/main/java/com/sparta/backend/utils/TestMailController.java
  src/main/resources/templates/email.html
  src/main/resources/templates/email01.html
  src/main/resources/templates/email02.html
  src/main/resources/templates/email03.html
Labels: 🛠 리팩토링

#217 hotfix: 이메일 수정 및 이미지파일 이름 최대길이 수정
  readme.md
  src/main/java/com/sparta/backend/model/Member.java
  src/main/resources/application-prod.yml
Labels: ❗️ 긴급

#219 feat, refactoring: DTO로 폴더 가져와서 메인페이지, 마이페이지에 보내기, 메인페이지 폴더 추천 로직 수정
  src/main/java/com/sparta/backend/controller/MainPageArticleFolderController.java
  src/main/java/com/sparta/backend/controller/MainPageController.java
  src/main/java/com/sparta/backend/model/Member.java
  src/main/java/com/sparta/backend/repository/ArticleFolderRepository.java
  src/main/java/com/sparta/backend/repository/MemberRepository.java
  src/main/java/com/sparta/backend/repositorycustom/ArticleFolderRepositoryCustom.java
  src/main/java/com/sparta/backend/repositorycustom/ArticleFolderRepositoryImpl.java
  src/main/java/com/sparta/backend/repositorycustom/MemberRepositoryCustom.java
  src/main/java/com/sparta/backend/repositorycustom/MemberRepositoryImpl.java
  src/main/java/com/sparta/backend/responseDto/ArticleFolderListResponseDto.java
  src/main/java/com/sparta/backend/responseDto/MainPageArticleFolderResponseDto.java
  src/main/java/com/sparta/backend/service/MainPageService.java
  src/main/java/com/sparta/backend/serviceImpl/ArticleFolderServiceImpl.java
  src/main/java/com/sparta/backend/serviceImpl/ArticleServiceImpl.java
  src/main/java/com/sparta/backend/serviceImpl/MainPageServiceImpl.java
  src/main/java/com/sparta/backend/serviceImpl/MyPageServiceImpl.java
  src/main/java/com/sparta/backend/utils/RandomGenerator.java
  src/test/java/com/sparta/backend/repository/ArticleFolderRepositoryTest.java
Labels: 🚀 기능추가, 🛠 리팩토링

#221 feat, refactoring, dependencies : DTO로 폴더 가져와서 메인페이지, 마이페이지에 보내기, 메인페이지 폴더 추천 로직 수정, swagger 제거 및 컨트롤러 스웨거 코드 제거
  .DS_Store
  build.gradle
  src/main/java/com/sparta/backend/SwaggerConfig.java
  src/main/java/com/sparta/backend/controller/ArticleController.java
  src/main/java/com/sparta/backend/controller/ArticleFolderController.java
  src/main/java/com/sparta/backend/controller/MainPageArticleFolderController.java
  src/main/java/com/sparta/backend/controller/MainPageController.java
  src/main/java/com/sparta/backend/controller/MyPageController.java
  src/main/java/com/sparta/backend/model/Member.java
  src/main/java/com/sparta/backend/repository/ArticleFolderRepository.java
  src/main/java/com/sparta/backend/repository/MemberRepository.java
  src/main/java/com/sparta/backend/repositorycustom/ArticleFolderRepositoryCustom.java
  src/main/java/com/sparta/backend/repositorycustom/ArticleFolderRepositoryImpl.java
  src/main/java/com/sparta/backend/repositorycustom/MemberRepositoryCustom.java
  src/main/java/com/sparta/backend/repositorycustom/MemberRepositoryImpl.java
  src/main/java/com/sparta/backend/responseDto/ArticleFolderListResponseDto.java
  src/main/java/com/sparta/backend/responseDto/MainPageArticleFolderResponseDto.java
  src/main/java/com/sparta/backend/service/MainPageService.java
  src/main/java/com/sparta/backend/serviceImpl/ArticleFolderServiceImpl.java
  src/main/java/com/sparta/backend/serviceImpl/ArticleServiceImpl.java
  src/main/java/com/sparta/backend/serviceImpl/MainPageServiceImpl.java
  src/main/java/com/sparta/backend/serviceImpl/MyPageServiceImpl.java
  src/main/java/com/sparta/backend/utils/RandomGenerator.java
Labels: 🚀 기능추가, 🥊 배포, 🛠 리팩토링

#225 refactoring: 폴더 리스트 Dto에 폴더의 주인 아이디 추가
  src/main/java/com/sparta/backend/controller/SearchPageControllerTest.java
  src/main/java/com/sparta/backend/repositorycustom/ArticleFolderRepositoryImpl.java
  src/main/java/com/sparta/backend/responseDto/MainPageArticleFolderResponseDto.java
  src/test/java/com/sparta/backend/repository/FavoriteRepositoryTest.java
Labels: 🛠 리팩토링

#226 refactoring: 폴더 리스트 Dto에 폴더의 주인 아이디 추가
  src/main/java/com/sparta/backend/controller/SearchPageControllerTest.java
  src/main/java/com/sparta/backend/repositorycustom/ArticleFolderRepositoryImpl.java
  src/main/java/com/sparta/backend/responseDto/MainPageArticleFolderResponseDto.java
  src/test/java/com/sparta/backend/repository/FavoriteRepositoryTest.java
Labels: 🛠 리팩토링

#235 feat, refactoring: 메인페이지 500 에러 외 다수 코드 수정
  src/main/java/com/sparta/backend/controller/ArticleFolderController.java
  src/main/java/com/sparta/backend/repository/FavoriteRepository.java
  src/main/java/com/sparta/backend/repository/MemberRepository.java
  src/main/java/com/sparta/backend/repositorycustom/ArticleFolderRepositoryCustom.java
  src/main/java/com/sparta/backend/repositorycustom/ArticleFolderRepositoryImpl.java
  src/main/java/com/sparta/backend/repositorycustom/MemberRepositoryCustom.java
  src/main/java/com/sparta/backend/repositorycustom/MemberRepositoryImpl.java
  src/main/java/com/sparta/backend/responseDto/ArticleFolderListResponseDto.java
  src/main/java/com/sparta/backend/responseDto/ArticlesInFolderResponseDto.java
  src/main/java/com/sparta/backend/responseDto/MemberArticleFolderHashtagInfoDto.java
  src/main/java/com/sparta/backend/responseDto/MemberHashtagInfoDto.java
  src/main/java/com/sparta/backend/service/ArticleFolderService.java
  src/main/java/com/sparta/backend/serviceImpl/ArticleFolderServiceImpl.java
  src/main/java/com/sparta/backend/serviceImpl/MainPageServiceImpl.java
  src/main/java/com/sparta/backend/serviceImpl/MyPageServiceImpl.java
  src/test/java/com/sparta/backend/serviceImpl/ArticleFolderServiceTest.java
Labels: 🚀 기능추가, 🛠 리팩토링

#238 refactoring: 메인페이지 폴더 내려주는 사이즈 오류 수정
  README.md
  src/main/java/com/sparta/backend/serviceImpl/MainPageServiceImpl.java
Labels: 🛠 리팩토링

#239 refactoring: 메인페이지 폴더 내려주는 사이즈 오류 수정
  README.md
  src/main/java/com/sparta/backend/serviceImpl/MainPageServiceImpl.java
Labels: 🛠 리팩토링
