Repository social-bookmark-9/backend, pull requests merged in 2022-03, with the labels that each got.

#16 feat: 카카오 OAuth JWT 발행
  src/main/java/com/sparta/backend/controller/ArticleFolderController.java
  src/main/java/com/sparta/backend/controller/OauthController.java
  src/main/java/com/sparta/backend/jwt/JwtAuthenticationFilter.java
  src/main/java/com/sparta/backend/jwt/JwtTokenProvider.java
  src/main/java/com/sparta/backend/model/Member.java
  src/main/java/com/sparta/backend/model/MemberRoleEnum.java
  src/main/java/com/sparta/backend/oauthDto/KakaoUserInfoRequestDto.java
  src/main/java/com/sparta/backend/oauthDto/KakaoUserInfoResponseDto.java
  src/main/java/com/sparta/backend/repository/MemberRepository.java
  src/main/java/com/sparta/backend/security/CustomMemberDetailService.java
  src/main/java/com/sparta/backend/security/WebConfig.java
  src/main/java/com/sparta/backend/security/WebSecurityConfig.java
  src/main/java/com/sparta/backend/service/OauthService.java
  src/test/java/com/sparta/backend/MappingTest.java
Labels: 🚀 기능추가, ⚙️ 환경설정

#19 feat: 회원가입 api 추가
  src/main/java/com/sparta/backend/controller/OauthController.java
  src/main/java/com/sparta/backend/oauthDto/KakaoMemberInfoRequestDto.java
  src/main/java/com/sparta/backend/oauthDto/KakaoMemberInfoResponseDto.java
  src/main/java/com/sparta/backend/oauthDto/KakaoMemberRegisterRequestDto.java
  src/main/java/com/sparta/backend/service/OauthService.java
  src/test/java/com/sparta/backend/MappingTest.java
Labels: 🚀 기능추가

#23 refactor: Oauth 기능 관련 리팩토링
  src/main/java/com/sparta/backend/controller/OauthController.java
  src/main/java/com/sparta/backend/model/Member.java
  src/main/java/com/sparta/backend/oauthDto/KakaoMemberInfoRequestDto.java
  src/main/java/com/sparta/backend/oauthDto/KakaoMemberInfoResponseDto.java
  src/main/java/com/sparta/backend/oauthDto/KakaoMemberRegisterRequestDto.java
  src/main/java/com/sparta/backend/security/WebSecurityConfig.java
  src/main/java/com/sparta/backend/service/OauthService.java
Labels: 🛠 리팩토링

#24 feat: JWT 예외처리 추가
  src/main/java/com/sparta/backend/controller/OauthController.java
  src/main/java/com/sparta/backend/jwt/JwtTokenProvider.java
  src/main/java/com/sparta/backend/security/CustomAccessDeniedHandler.java
  src/main/java/com/sparta/backend/security/CustomAuthenticationEntryPoint.java
  src/main/java/com/sparta/backend/security/WebSecurityConfig.java
Labels: 🚀 기능추가

#27 feat: Article API 생성, 테스트코드 작성
  src/main/java/com/sparta/backend/controller/ArticleController.java
  src/main/java/com/sparta/backend/controller/ArticleFolderController.java
  src/main/java/com/sparta/backend/exception/ErrorCode.java
  src/main/java/com/sparta/backend/exception/testException.java
  src/main/java/com/sparta/backend/model/Alarm.java
  src/main/java/com/sparta/backend/model/Article.java
  src/main/java/com/sparta/backend/model/ArticleFolder.java
  src/main/java/com/sparta/backend/model/Favorite.java
  src/main/java/com/sparta/backend/model/Hashtag.java
  src/main/java/com/sparta/backend/model/Member.java
  src/main/java/com/sparta/backend/requestDto/ArticleCreateRequestDto.java
  src/main/java/com/sparta/backend/service/ArticleService.java
  src/main/java/com/sparta/backend/serviceImpl/ArticleServiceImpl.java
  src/main/java/com/sparta/backend/validator/ArticleValidator.java
  src/test/java/com/sparta/backend/MappingTest.java
  src/test/java/com/sparta/backend/repository/ArticleRepositoryTest.java
Labels: 🚀 기능추가, 🧪 테스트작성

#30 feat: Refresh 토큰 발행
  src/main/java/com/sparta/backend/controller/OauthController.java
  src/main/java/com/sparta/backend/jwt/JwtAuthenticationFilter.java
  src/main/java/com/sparta/backend/jwt/JwtTokenProvider.java
  src/main/java/com/sparta/backend/model/RefreshToken.java
  src/main/java/com/sparta/backend/oauthDto/TokenDto.java
  src/main/java/com/sparta/backend/oauthDto/TokenRequestDto.java
  src/main/java/com/sparta/backend/repository/RefreshTokenRepository.java
  src/main/java/com/sparta/backend/service/OauthService.java
  src/test/java/com/sparta/backend/repository/ArticleRepositoryTest.java
Labels: 🚀 기능추가

#33 refactor: 프로필 이미지 Member 필드에 추가
  src/main/java/com/sparta/backend/controller/OauthController.java
  src/main/java/com/sparta/backend/model/Member.java
  src/main/java/com/sparta/backend/oauthDto/KakaoMemberInfoRequestDto.java
  src/main/java/com/sparta/backend/oauthDto/KakaoMemberRegisterRequestDto.java
  src/main/java/com/sparta/backend/service/OauthService.java
Labels: 🚀 기능추가, 🛠 리팩토링

#34 feat: 아티클 폴더 생성, 삭제, 수정, 폴더에 속한 모든 아티클 조회
  src/main/java/com/sparta/backend/controller/ArticleFolderController.java
  src/main/java/com/sparta/backend/message/DataListMessage.java
  src/main/java/com/sparta/backend/model/ArticleFolder.java
  src/main/java/com/sparta/backend/repository/ArticleFolderRepository.java
  src/main/java/com/sparta/backend/requestDto/ArticleFolderCreateRequestDto.java
  src/main/java/com/sparta/backend/requestDto/ArticleFolderNameUpdateRequestDto.java
  src/main/java/com/sparta/backend/responseDto/ArticlesInFolderResponseDto.java
  src/main/java/com/sparta/backend/service/ArticleFolderService.java
  src/main/java/com/sparta/backend/serviceImpl/ArticleFolderServiceImpl.java
  src/test/java/com/sparta/backend/service/ArticleFolderServiceTest.java
Labels: 🚀 기능추가, 🛠 리팩토링

#37 refactor: 긴급 수정 - 프론트와 Oauth 연결 중 수정사항 발생 및 시크릿 키 감춤
  src/main/java/com/sparta/backend/controller/OauthController.java
  src/main/java/com/sparta/backend/jwt/JwtTokenProvider.java
  src/main/java/com/sparta/backend/model/Member.java
  src/main/java/com/sparta/backend/security/WebSecurityConfig.java
  src/main/java/com/sparta/backend/service/OauthService.java
  src/main/resources/static/index.html
Labels: 🐞 버그, 🛠 리팩토링, ❗️ 긴급

#41 feat: 메일 서버 스터디중...
  build.gradle
  src/main/java/com/sparta/backend/controller/EmailController.java
  src/main/java/com/sparta/backend/message/EmailMessage.java
  src/main/java/com/sparta/backend/service/EmailService.java
  src/main/java/com/sparta/backend/service/OauthService.java
Labels: 🗂 의존성설치, 🚀 기능추가, ⚙️ 환경설정

#54 feat: 리뷰 수정, 리뷰 가리기 API 추가, 박싱 타입들 언방식으로 변경
  src/main/java/com/sparta/backend/BackendApplication.java
  src/main/java/com/sparta/backend/controller/ArticleController.java
  src/main/java/com/sparta/backend/controller/ArticleFolderController.java
  src/main/java/com/sparta/backend/controller/EmailController.java
  src/main/java/com/sparta/backend/controller/OauthController.java
  src/main/java/com/sparta/backend/exception/testException.java
  src/main/java/com/sparta/backend/message/DataMessage.java
  src/main/java/com/sparta/backend/message/DefaultMessage.java
  src/main/java/com/sparta/backend/message/EmailMessage.java
  src/main/java/com/sparta/backend/message/RestResponseMessage.java
  src/main/java/com/sparta/backend/model/Alarm.java
  src/main/java/com/sparta/backend/model/Article.java
  src/main/java/com/sparta/backend/model/ArticleFolder.java
  src/main/java/com/sparta/backend/model/Favorite.java
  src/main/java/com/sparta/backend/model/Hashtag.java
  src/main/java/com/sparta/backend/model/Member.java
  src/main/java/com/sparta/backend/model/RefreshToken.java
  src/main/java/com/sparta/backend/requestDto/ArticleCreateRequestDto.java
  src/main/java/com/sparta/backend/requestDto/ArticleReviewRequestDto.java
  src/main/java/com/sparta/backend/requestDto/ArticleUpdateRequestDto.java
  src/main/java/com/sparta/backend/responseDto/ArticleResponseDto.java
  src/main/java/com/sparta/backend/responseDto/ArticleReviewResponseDto.java
  src/main/java/com/sparta/backend/service/ArticleFolderService.java
  src/main/java/com/sparta/backend/service/ArticleService.java
  src/main/java/com/sparta/backend/service/EmailService.java
  src/main/java/com/sparta/backend/service/OauthService.java
  src/main/java/com/sparta/backend/serviceImpl/ArticleServiceImpl.java
  src/test/java/com/sparta/backend/MappingTest.java
  src/test/java/com/sparta/backend/repository/ArticleRepositoryTest.java
  src/test/java/com/sparta/backend/serviceImpl/ArticleServiceImplTest.java
Labels: 🚀 기능추가, 🛠 리팩토링

#55 feat: 스케쥴러로 자동 메일 발송하기 외 1
  src/main/java/com/sparta/backend/BackendApplication.java
  src/main/java/com/sparta/backend/controller/EmailController.java
  src/main/java/com/sparta/backend/controller/OauthController.java
  src/main/java/com/sparta/backend/controller/ReminderController.java
  src/main/java/com/sparta/backend/jwt/JwtTokenProvider.java
  src/main/java/com/sparta/backend/model/Member.java
  src/main/java/com/sparta/backend/model/Reminder.java
  src/main/java/com/sparta/backend/repository/ReminderRepository.java
  src/main/java/com/sparta/backend/requestDto/ReminderRequestDto.java
  src/main/java/com/sparta/backend/service/EmailService.java
  src/main/java/com/sparta/backend/service/OauthService.java
  src/main/java/com/sparta/backend/service/ReminderService.java
  src/main/java/com/sparta/backend/utils/EmailScheduler.java
  src/main/resources/static/index.html
  src/test/java/com/sparta/backend/MappingTest.java
  src/test/java/com/sparta/backend/repository/ReminderRepositoryTest.java
Labels: 🗂 의존성설치, 🚀 기능추가, 🛠 리팩토링

#57 feat: 카카오 로그아웃 기능 추가
  src/main/java/com/sparta/backend/controller/OauthController.java
  src/main/java/com/sparta/backend/controller/ReminderController.java
  src/main/java/com/sparta/backend/repository/RefreshTokenRepository.java
  src/main/java/com/sparta/backend/service/OauthService.java
  src/main/resources/static/index.html
Labels: 🚀 기능추가

#61 refactor: 긴급 DB 수정 1차
  build.gradle
  src/main/java/com/sparta/backend/model/Article.java
  src/main/java/com/sparta/backend/model/Hashtag.java
  src/main/java/com/sparta/backend/model/Reminder.java
  src/main/java/com/sparta/backend/requestDto/ArticleCreateRequestDto.java
  src/main/java/com/sparta/backend/requestDto/ReminderRequestDto.java
  src/main/java/com/sparta/backend/service/ReminderService.java
  src/main/java/com/sparta/backend/serviceImpl/ArticleServiceImpl.java
  src/test/java/com/sparta/backend/MappingTest.java
  src/test/java/com/sparta/backend/repository/ReminderRepositoryTest.java
  src/test/java/com/sparta/backend/serviceImpl/ArticleServiceImplTest.java
Labels: 🐞 버그, 🛠 리팩토링, ❗️ 긴급

#63 refactoring, feat: 폴더에 있는 모든 아티클 조회 리팩토링 및 좋아요 추가, 삭제
  src/main/java/com/sparta/backend/controller/ArticleFolderController.java
  src/main/java/com/sparta/backend/exception/testException.java
  src/main/java/com/sparta/backend/model/Article.java
  src/main/java/com/sparta/backend/model/ArticleFolder.java
  src/main/java/com/sparta/backend/model/Favorite.java
  src/main/java/com/sparta/backend/model/Hashtag.java
  src/main/java/com/sparta/backend/model/Member.java
  src/main/java/com/sparta/backend/repository/ArticleFolderRepository.java
  src/main/java/com/sparta/backend/repository/ArticleRepository.java
  src/main/java/com/sparta/backend/repository/FavoriteRepository.java
  src/main/java/com/sparta/backend/requestDto/ArticleFolderCreateRequestDto.java
  src/main/java/com/sparta/backend/requestDto/ArticleFolderNameUpdateRequestDto.java
  src/main/java/com/sparta/backend/responseDto/ArticlesInFolderResponseDto.java
  src/main/java/com/sparta/backend/responseDto/LikeAddOrRemoveResponseDto.java
  src/main/java/com/sparta/backend/service/ArticleFolderService.java
  src/main/java/com/sparta/backend/serviceImpl/ArticleFolderServiceImpl.java
  src/test/java/com/sparta/backend/MappingTest.java
  src/test/java/com/sparta/backend/repository/ArticleRepositoryTest.java
  src/test/java/com/sparta/backend/repository/ReminderRepositoryTest.java
  src/test/java/com/sparta/backend/service/ArticleFolderServiceTest.java
  src/test/java/com/sparta/backend/serviceImpl/ArticleFolderServiceTest.java
  src/test/java/com/sparta/backend/serviceImpl/ArticleServiceImplTest.java
Labels: 🐞 버그, 🚀 기능추가, 🧪 테스트작성, 🛠 리팩토링, ❗️ 긴급

#64 refactor : 테스트 제거
  src/main/java/com/sparta/backend/controller/ArticleController.java
  src/main/java/com/sparta/backend/controller/ArticleFolderController.java
  src/main/java/com/sparta/backend/message/RestResponseMessage.java
  src/main/java/com/sparta/backend/model/Article.java
  src/main/java/com/sparta/backend/requestDto/ArticleCreateRequestDto.java
  src/main/java/com/sparta/backend/requestDto/ReminderRequestDto.java
  src/main/java/com/sparta/backend/responseDto/ArticleResponseDto.java
  src/main/java/com/sparta/backend/responseDto/ArticleReviewHideResponseDto.java
  src/main/java/com/sparta/backend/service/ArticleService.java
  src/main/java/com/sparta/backend/serviceImpl/ArticleServiceImpl.java
Labels: 🛠 리팩토링

#70 feat: : 마이페이지 유저 정보 변경 기능 추가 / refactor: 로그인 할 때 유저정보 추가로 내려주기 / feat: 프로필 사진 업데이트용 S3 이미지 서버 생성
  build.gradle
  src/main/java/com/sparta/backend/amazons3/AmazonS3Config.java
  src/main/java/com/sparta/backend/amazons3/AmazonS3Controller.java
  src/main/java/com/sparta/backend/amazons3/AmazonS3Uploader.java
  src/main/java/com/sparta/backend/controller/MemberInfoController.java
  src/main/java/com/sparta/backend/controller/OauthController.java
  src/main/java/com/sparta/backend/model/Hashtag.java
  src/main/java/com/sparta/backend/model/Member.java
  src/main/java/com/sparta/backend/requestDto/MemberInfoEditRequestDto.java
  src/main/java/com/sparta/backend/responseDto/MemberLoginResponseDto.java
  src/main/java/com/sparta/backend/service/MemberInfoService.java
  src/main/java/com/sparta/backend/service/OauthService.java
Labels: 🗂 의존성설치, 🚀 기능추가, 🛠 리팩토링

#74 feat: 통합 에러 핸들링 정의
  src/main/java/com/sparta/backend/BackendApplication.java
  src/main/java/com/sparta/backend/controller/ArticleController.java
  src/main/java/com/sparta/backend/exception/BusinessException.java
  src/main/java/com/sparta/backend/exception/EntityNotFoundException.java
  src/main/java/com/sparta/backend/exception/ErrorCode.java
  src/main/java/com/sparta/backend/exception/ErrorCodeException.java
  src/main/java/com/sparta/backend/exception/ErrorCodeExceptionHandler.java
  src/main/java/com/sparta/backend/exception/ErrorCodeResponse.java
  src/main/java/com/sparta/backend/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/backend/exception/InvalidValueException.java
  src/main/java/com/sparta/backend/exception/testException.java
  src/main/java/com/sparta/backend/message/ErrorResponseMessage.java
  src/main/java/com/sparta/backend/message/RestResponseMessage.java
Labels: 🚀 기능추가

#75 emergency: 로그인 토큰 검증 과정 해결하기
  src/main/java/com/sparta/backend/controller/OauthController.java
  src/main/java/com/sparta/backend/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/backend/jwt/JwtAuthenticationFilter.java
  src/main/java/com/sparta/backend/jwt/JwtTokenProvider.java
  src/main/java/com/sparta/backend/model/Article.java
  src/main/java/com/sparta/backend/security/WebSecurityConfig.java
Labels: 🐞 버그, ❗️ 긴급

#79 feat: 마이페이지 내 사용자 정보, 남의 사용자 정보, 사용자 폴더 리스트 조회
  src/main/java/com/sparta/backend/controller/ArticleFolderController.java
  src/main/java/com/sparta/backend/controller/MyPageController.java
  src/main/java/com/sparta/backend/controller/OauthController.java
  src/main/java/com/sparta/backend/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/backend/model/ArticleFolder.java
  src/main/java/com/sparta/backend/model/Member.java
  src/main/java/com/sparta/backend/model/Timestamped.java
  src/main/java/com/sparta/backend/repository/ArticleFolderRepository.java
  src/main/java/com/sparta/backend/repository/FavoriteRepository.java
  src/main/java/com/sparta/backend/responseDto/ArticleFolderListDto.java
  src/main/java/com/sparta/backend/responseDto/MemberInfoDto.java
  src/main/java/com/sparta/backend/responseDto/MyPageResponseDto.java
  src/main/java/com/sparta/backend/service/MyPageService.java
  src/main/java/com/sparta/backend/serviceImpl/ArticleFolderServiceImpl.java
  src/main/java/com/sparta/backend/serviceImpl/MyPageServiceImpl.java
  src/test/java/com/sparta/backend/serviceImpl/ArticleFolderServiceTest.java
  src/test/java/com/sparta/backend/serviceImpl/MyPageServiceImplTest.java
  src/test/java/test.java
Labels: 🚀 기능추가

#81 feat: JWT 에러 핸들링
  src/main/java/com/sparta/backend/controller/OauthController.java
  src/main/java/com/sparta/backend/exception/ErrorCode.java
  src/main/java/com/sparta/backend/jwt/JwtAuthenticationFilter.java
  src/main/java/com/sparta/backend/jwt/JwtTokenProvider.java
  src/main/java/com/sparta/backend/security/CustomAccessDeniedHandler.java
  src/main/java/com/sparta/backend/security/CustomAuthenticationEntryPoint.java
  src/main/java/com/sparta/backend/security/JwtExceptionFilter.java
  src/main/java/com/sparta/backend/security/WebSecurityConfig.java
Labels: 🚀 기능추가

#82 feat: 해당 URL의 OG태그 가져오기
  build.gradle
  src/main/java/com/sparta/backend/lib/opengraph/MetaElement.java
  src/main/java/com/sparta/backend/lib/opengraph/OpenGraph.java
  src/main/java/com/sparta/backend/lib/opengraph/OpenGraphNamespace.java
  src/main/java/com/sparta/backend/model/Article.java
  src/main/java/com/sparta/backend/model/ArticleFolder.java
  src/main/java/com/sparta/backend/model/Reminder.java
  src/main/java/com/sparta/backend/requestDto/ArticleCreateRequestDto.java
  src/main/java/com/sparta/backend/requestDto/OGTagRequestDto.java
  src/main/java/com/sparta/backend/service/OauthService.java
  src/main/java/com/sparta/backend/serviceImpl/ArticleServiceImpl.java
  src/main/java/com/sparta/backend/utils/JsoupParser.java
  src/main/java/com/sparta/backend/utils/OpenGraphScrapper.java
  src/main/java/com/sparta/backend/utils/RandomGenerator.java
Labels: 🗂 의존성설치, 🛠 리팩토링, 🎉 작업완료

#88 emergency: 프론트엔드 테스트용 메인페이지 작성
  src/main/java/com/sparta/backend/controller/MainPageArticleFolderController.java
  src/main/java/com/sparta/backend/controller/MainPageController.java
  src/main/java/com/sparta/backend/controller/MainPageMemberController.java
  src/main/java/com/sparta/backend/jwt/JwtTokenProvider.java
Labels: ❗️ 긴급

#94 emergency: 미분류 컬렉션 쿼리 결과가 1개 이상 발생되는 버그 해결
  src/main/java/com/sparta/backend/controller/ArticleController.java
  src/main/java/com/sparta/backend/lib/opengraph/MetaElement.java
  src/main/java/com/sparta/backend/lib/opengraph/OpenGraph.java
  src/main/java/com/sparta/backend/lib/opengraph/OpenGraphNamespace.java
  src/main/java/com/sparta/backend/model/Article.java
  src/main/java/com/sparta/backend/repository/ArticleFolderRepository.java
  src/main/java/com/sparta/backend/repository/ArticleRepository.java
  src/main/java/com/sparta/backend/responseDto/ArticleReviewResponseDto.java
  src/main/java/com/sparta/backend/responseDto/ArticleReviewResponseDtos.java
  src/main/java/com/sparta/backend/service/ArticleService.java
  src/main/java/com/sparta/backend/serviceImpl/ArticleServiceImpl.java
  src/main/java/com/sparta/backend/utils/JsoupParser.java
  src/test/java/com/sparta/backend/serviceImpl/ArticleFolderServiceTest.java
  src/test/java/com/sparta/backend/serviceImpl/MyPageServiceImplTest.java
Labels: 🐞 버그, ❗️ 긴급

#97 bug: test코드 수정
  $buildDir/generated/querydsl/com/sparta/backend/model/QArticle.java
  $buildDir/generated/querydsl/com/sparta/backend/model/QReminder.java
  build.gradle
  src/test/java/com/sparta/backend/nplus1/nplus1test.java
  src/test/java/com/sparta/backend/serviceImpl/ArticleFolderServiceTest.java
Labels: 🐞 버그, ❗️ 긴급

#99 feat: 리뷰 리스트 추가
  $buildDir/generated/querydsl/com/sparta/backend/model/QAlarm.java
  $buildDir/generated/querydsl/com/sparta/backend/model/QArticle.java
  $buildDir/generated/querydsl/com/sparta/backend/model/QArticleFolder.java
  $buildDir/generated/querydsl/com/sparta/backend/model/QFavorite.java
  $buildDir/generated/querydsl/com/sparta/backend/model/QHashtag.java
  $buildDir/generated/querydsl/com/sparta/backend/model/QMember.java
  $buildDir/generated/querydsl/com/sparta/backend/model/QRefreshToken.java
  $buildDir/generated/querydsl/com/sparta/backend/model/QReminder.java
  $buildDir/generated/querydsl/com/sparta/backend/model/QTimestamped.java
  src/main/java/com/sparta/backend/controller/ArticleController.java
  src/main/java/com/sparta/backend/requestDto/ArticleCreateRequestDto.java
  src/main/java/com/sparta/backend/requestDto/ArticleReviewRequestDto.java
  src/main/java/com/sparta/backend/responseDto/ArticleReviewResponseDto.java
  src/main/java/com/sparta/backend/serviceImpl/ArticleServiceImpl.java
Labels: 🚀 기능추가

#106 feat: 더미데이터 기능 추가, 메인페이지 추천 로직 리팩토링
  src/main/java/com/sparta/backend/controller/MainPageArticleController.java
  src/main/java/com/sparta/backend/controller/MainPageController.java
  src/main/java/com/sparta/backend/controller/MainPageMemberController.java
  src/main/java/com/sparta/backend/repository/ArticleRepository.java
  src/main/java/com/sparta/backend/repository/MemberRepository.java
  src/main/java/com/sparta/backend/responseDto/RecommendedMemberResponseDto.java
  src/main/java/com/sparta/backend/service/MainPageService.java
  src/main/java/com/sparta/backend/utils/DummyArticleFolder.java
  src/main/java/com/sparta/backend/utils/DummyUser.java
  src/main/java/com/sparta/backend/utils/RandomGenerator.java
Labels: 🚀 기능추가, 🛠 리팩토링

#115 refactoring: 아티클 폴더 서비스로직 수정 및 리팩토링
  src/main/java/com/sparta/backend/controller/ArticleFolderController.java
  src/main/java/com/sparta/backend/controller/MainPageArticleFolderController.java
  src/main/java/com/sparta/backend/controller/MyPageController.java
  src/main/java/com/sparta/backend/model/ArticleFolder.java
  src/main/java/com/sparta/backend/model/Favorite.java
  src/main/java/com/sparta/backend/responseDto/ArticleFolderListResponseDto.java
  src/main/java/com/sparta/backend/responseDto/ArticleFolderNameAndIdResponseDto.java
  src/main/java/com/sparta/backend/responseDto/ArticlesInFolderResponseDto.java
  src/main/java/com/sparta/backend/responseDto/ArticlesInfoInFolderResponseDto.java
  src/main/java/com/sparta/backend/responseDto/LikeAddOrRemoveResponseDto.java
  src/main/java/com/sparta/backend/service/ArticleFolderService.java
  src/main/java/com/sparta/backend/serviceImpl/ArticleFolderServiceImpl.java
  src/test/java/com/sparta/backend/serviceImpl/ArticleFolderServiceTest.java
Labels: 🐞 버그, 🛠 리팩토링

#116 feat: 아티클 폴더 비공개일 때 아티클 관련 로직 작성, 아티클 제거 API 작성
  src/main/java/com/sparta/backend/amazons3/AmazonS3Uploader.java
  src/main/java/com/sparta/backend/controller/ArticleController.java
  src/main/java/com/sparta/backend/exception/ArticleAccessDeniedException.java
  src/main/java/com/sparta/backend/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/backend/repository/ArticleRepository.java
  src/main/java/com/sparta/backend/service/ArticleService.java
  src/main/java/com/sparta/backend/serviceImpl/ArticleServiceImpl.java
Labels: 🚀 기능추가, 🛠 리팩토링

#117 refactor: 더미생성코드 수정
  src/main/java/com/sparta/backend/utils/DummyArticleFolder.java
Labels: 🛠 리팩토링

#121 refactor: serviceImpl 수정
  .gitignore
  src/main/java/com/sparta/backend/controller/ReminderController.java
  src/main/java/com/sparta/backend/service/MemberInfoService.java
  src/main/java/com/sparta/backend/service/OauthService.java
  src/main/java/com/sparta/backend/service/ReminderService.java
  src/main/java/com/sparta/backend/serviceImpl/MemberInfoServiceImpl.java
  src/main/java/com/sparta/backend/serviceImpl/OauthServiceImpl.java
  src/main/java/com/sparta/backend/serviceImpl/ReminderServiceImpl.java
  src/main/java/com/sparta/backend/utils/DummyArticleFolder.java
  src/main/java/com/sparta/backend/utils/DummyData.java
  src/main/java/com/sparta/backend/utils/DummyRequestDto.java
  src/main/java/com/sparta/backend/utils/DummyUser.java
  src/test/java/com/sparta/backend/serviceImpl/ArticleFolderServiceTest.java
Labels: 🚀 기능추가, 🛠 리팩토링

#124 feat: 아티클 생성 관련 API
  .DS_Store
  src/main/java/com/sparta/backend/controller/ArticleController.java
  src/main/java/com/sparta/backend/controller/ReminderController.java
  src/main/java/com/sparta/backend/exception/ErrorCode.java
  src/main/java/com/sparta/backend/exception/InvalidValueException.java
  src/main/java/com/sparta/backend/model/Article.java
  src/main/java/com/sparta/backend/model/Hashtag.java
  src/main/java/com/sparta/backend/requestDto/ArticleTitleRequestDto.java
  src/main/java/com/sparta/backend/requestDto/HashtagUpdateRequestDto.java
  src/main/java/com/sparta/backend/responseDto/ArticleGetResponseDto.java
  src/main/java/com/sparta/backend/responseDto/ArticleTitleResponseDto.java
  src/main/java/com/sparta/backend/responseDto/HashtagResponseDto.java
  src/main/java/com/sparta/backend/service/ArticleService.java
  src/main/java/com/sparta/backend/serviceImpl/ArticleFolderServiceImpl.java
  src/main/java/com/sparta/backend/serviceImpl/ArticleServiceImpl.java
Labels: 🚀 기능추가, 🛠 리팩토링

#126 feat: 리마인더 이메일 수정 및 메인페이지 리팩토링
  build.gradle
  src/main/java/com/sparta/backend/BackendApplication.java
  src/main/java/com/sparta/backend/controller/MainPageArticleController.java
  src/main/java/com/sparta/backend/controller/MainPageArticleFolderController.java
  src/main/java/com/sparta/backend/controller/MainPageController.java
  src/main/java/com/sparta/backend/controller/MainPageMemberController.java
  src/main/java/com/sparta/backend/controller/MemberInfoController.java
  src/main/java/com/sparta/backend/model/Member.java
  src/main/java/com/sparta/backend/repository/ArticleFolderRepository.java
  src/main/java/com/sparta/backend/repository/ReminderRepository.java
  src/main/java/com/sparta/backend/requestDto/MemberInfoEditRequestDto.java
  src/main/java/com/sparta/backend/service/MainPageService.java
  src/main/java/com/sparta/backend/service/MemberInfoService.java
  src/main/java/com/sparta/backend/serviceImpl/MainPageServiceImpl.java
  src/main/java/com/sparta/backend/serviceImpl/MemberInfoServiceImpl.java
  src/main/java/com/sparta/backend/serviceImpl/OauthServiceImpl.java
  src/main/java/com/sparta/backend/utils/DummyData.java
  src/main/java/com/sparta/backend/utils/EmailScheduler.java
  src/main/java/com/sparta/backend/utils/RandomGenerator.java
  src/main/java/com/sparta/backend/utils/TestMailController.java
  src/main/resources/templates/mail.html
Labels: 🗂 의존성설치, 🚀 기능추가, 🛠 리팩토링

#132 feat: 아티클의 폴더 변경, 타인의 아티클 폴더에서 모든 아티클 가져오기
  src/main/java/com/sparta/backend/controller/ArticleController.java
  src/main/java/com/sparta/backend/exception/ErrorCode.java
  src/main/java/com/sparta/backend/model/Article.java
  src/main/java/com/sparta/backend/requestDto/ArticleFolderChangeUpdateRequestDto.java
  src/main/java/com/sparta/backend/requestDto/ArticleUpdateRequestDto.java
  src/main/java/com/sparta/backend/service/ArticleService.java
  src/main/java/com/sparta/backend/serviceImpl/ArticleServiceImpl.java
Labels: 🚀 기능추가

#134 refactoring: 폴더 안 아티클 조회 비로그인 사용자에게도 허용, 폴더 이름 목록 조회 및 각종 코드 수정
  src/main/java/com/sparta/backend/controller/ArticleFolderController.java
  src/main/java/com/sparta/backend/model/Member.java
  src/main/java/com/sparta/backend/responseDto/ArticleFolderListResponseDto.java
  src/main/java/com/sparta/backend/responseDto/ArticleFolderNameAndIdResponseDto.java
  src/main/java/com/sparta/backend/responseDto/ArticlesInFolderResponseDto.java
  src/main/java/com/sparta/backend/responseDto/ArticlesInfoInFolderResponseDto.java
  src/main/java/com/sparta/backend/responseDto/MyPageResponseDto.java
  src/main/java/com/sparta/backend/service/ArticleFolderService.java
  src/main/java/com/sparta/backend/serviceImpl/ArticleFolderServiceImpl.java
  src/test/java/com/sparta/backend/serviceImpl/ArticleFolderServiceTest.java
Labels: 🛠 리팩토링

#138 refactor: 메인페이지 하드코딩 수정 및 Reminder Entity 수정
  src/main/java/com/sparta/backend/controller/MainPageController.java
  src/main/java/com/sparta/backend/model/Reminder.java
  src/main/java/com/sparta/backend/repository/ArticleFolderRepository.java
  src/main/java/com/sparta/backend/repository/ReminderRepository.java
  src/main/java/com/sparta/backend/requestDto/ReminderRequestDto.java
  src/main/java/com/sparta/backend/responseDto/ReminderResponseDto.java
  src/main/java/com/sparta/backend/serviceImpl/MainPageServiceImpl.java
  src/main/java/com/sparta/backend/serviceImpl/ReminderServiceImpl.java
  src/main/java/com/sparta/backend/utils/EmailScheduler.java
  src/main/java/com/sparta/backend/utils/RandomGenerator.java
  src/main/java/com/sparta/backend/utils/TestMailController.java
  src/main/resources/templates/email.html
  src/main/resources/templates/mail.html
Labels: 🛠 리팩토링

#141 refactor: 프론트 연결용 redirect url 추가
  src/main/java/com/sparta/backend/controller/OauthController.java
  src/main/java/com/sparta/backend/model/ArticleFolder.java
  src/main/java/com/sparta/backend/model/Favorite.java
  src/main/java/com/sparta/backend/model/Hashtag.java
  src/main/java/com/sparta/backend/model/Member.java
  src/main/java/com/sparta/backend/model/RefreshToken.java
  src/main/java/com/sparta/backend/serviceImpl/MainPageServiceImpl.java
  src/main/java/com/sparta/backend/serviceImpl/OauthServiceImpl.java
  src/main/resources/static/index.html
Labels: 🛠 리팩토링

#142 dependencies: Mockito 설치
  build.gradle
  src/main/java/com/sparta/backend/controller/ArticleController.java
  src/main/java/com/sparta/backend/serviceImpl/ArticleServiceImpl.java
Labels: 🗂 의존성설치

#145 feat: 리뷰 내려줄 때 아티클 타이틀도 함께 내려주기, 리마인더 생성되지 않았을 때, null 처리
  src/main/java/com/sparta/backend/responseDto/ArticleReviewResponseDto.java
  src/main/java/com/sparta/backend/serviceImpl/ArticleServiceImpl.java
Labels: 🐞 버그, 🚀 기능추가

#147 refactor: CI / CD 용 property 수정
  src/main/resources/application.properties
Labels: 🛠 리팩토링

#150 refactor: yml 로 교체
  .gitignore
  src/main/java/com/sparta/backend/amazons3/AmazonS3Config.java
  src/main/resources/application-prod.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: 🛠 리팩토링

#153 refactor: 테스트 yml 수정
  src/test/java/com/sparta/backend/BackendApplicationTests.java
  src/test/java/com/sparta/backend/nplus1/nplus1test.java
  src/test/java/com/sparta/backend/serviceImpl/ArticleFolderServiceTest.java
  src/test/java/com/sparta/backend/serviceImpl/MyPageServiceImplTest.java
Labels: 🛠 리팩토링

#157 feat: 리뷰 응답시 null 체크, 리뷰에 타이틀 함께 응답
  .gitignore
  src/main/java/com/sparta/backend/.DS_Store
  src/main/java/com/sparta/backend/serviceImpl/ArticleServiceImpl.java
  src/main/resources/.DS_Store
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: 🚀 기능추가

#158 refactor: DataIntegrityViolationException 오류 해결 (update 시 테스트코드 데이터 때문)
  src/main/java/com/sparta/backend/requestDto/ReminderRequestDto.java
  src/test/java/com/sparta/backend/nplus1/nplus1test.java
  src/test/java/com/sparta/backend/serviceImpl/ArticleFolderServiceTest.java
  src/test/java/com/sparta/backend/serviceImpl/MyPageServiceImplTest.java
  src/test/java/test.java
Labels: 🛠 리팩토링

#159 refactor: CI update
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/com/sparta/backend/nplus1/nplus1test.java
  src/test/java/com/sparta/backend/serviceImpl/ArticleFolderServiceTest.java
  src/test/java/com/sparta/backend/serviceImpl/MyPageServiceImplTest.java
Labels: 🛠 리팩토링

#166 feat: 이메일 중복 기능 추가 및 git 버그 확인
  src/main/java/com/sparta/backend/controller/MemberInfoController.java
  src/main/java/com/sparta/backend/repository/MemberRepository.java
  src/main/java/com/sparta/backend/requestDto/MemberNameDuplicateDto.java
  src/main/java/com/sparta/backend/service/MemberInfoService.java
  src/main/java/com/sparta/backend/serviceImpl/MemberInfoServiceImpl.java
  src/main/resources/application-prod.yml
Labels: 🐞 버그, 🚀 기능추가

#169 deploy : CICD를 위한 배포작업
  src/main/java/com/sparta/backend/controller/MemberInfoController.java
  src/main/java/com/sparta/backend/repository/MemberRepository.java
  src/main/java/com/sparta/backend/requestDto/MemberNameDuplicateDto.java
  src/main/java/com/sparta/backend/responseDto/ArticleFolderListResponseDto.java
  src/main/java/com/sparta/backend/service/MemberInfoService.java
  src/main/java/com/sparta/backend/service/MyPageService.java
  src/main/java/com/sparta/backend/serviceImpl/ArticleServiceImpl.java
  src/main/java/com/sparta/backend/serviceImpl/MemberInfoServiceImpl.java
  src/main/java/com/sparta/backend/serviceImpl/MyPageServiceImpl.java
  src/main/resources/application-prod.yml
  src/test/java/com/sparta/backend/serviceImpl/ArticleFolderServiceTest.java
  src/test/java/com/sparta/backend/serviceImpl/MyPageServiceImplTest.java
Labels: 🥊 배포

#170 feat: 로깅 전략 추가
  .gitignore
  src/main/java/com/sparta/backend/utils/TestMailController.java
  src/main/resources/logback-spring.xml
  src/main/resources/templates/email.html
  src/test/java/com/sparta/backend/BackendApplicationTests.java
  src/test/java/com/sparta/backend/nplus1/nplus1test.java
  src/test/java/com/sparta/backend/serviceImpl/ArticleFolderServiceTest.java
  src/test/java/com/sparta/backend/serviceImpl/MyPageServiceImplTest.java
Labels: 🚀 기능추가

#174 refactor: 이메일 메세지 수정 및 리프레시 토큰 제거 수정
  src/main/java/com/sparta/backend/controller/MemberInfoController.java
  src/main/java/com/sparta/backend/controller/OauthController.java
  src/main/java/com/sparta/backend/repository/ArticleFolderRepository.java
  src/main/resources/logback-spring.xml
  src/test/java/com/sparta/backend/serviceImpl/ReminderServiceTest.java
Labels: 🛠 리팩토링

#177 feat: 중복 확인 메세지 수정 및 쉘 스크립트 작성
  build.gradle
  src/main/java/com/sparta/backend/controller/MemberInfoController.java
  src/main/java/com/sparta/backend/controller/OauthController.java
  src/main/java/com/sparta/backend/repository/ArticleFolderRepository.java
  src/main/java/com/sparta/backend/responseDto/ArticleFolderListResponseDto.java
  src/main/java/com/sparta/backend/service/MyPageService.java
  src/main/java/com/sparta/backend/serviceImpl/ArticleServiceImpl.java
  src/main/java/com/sparta/backend/utils/TestMailController.java
  src/main/resources/logback-spring.xml
  src/test/java/com/sparta/backend/serviceImpl/ReminderServiceTest.java
Labels: 🚀 기능추가, 🥊 배포

#179 refactor: 멤버네임 method 변경
  src/main/java/com/sparta/backend/controller/MemberInfoController.java
  src/test/java/com/sparta/backend/serviceImpl/ReminderServiceTest.java
Labels: 🛠 리팩토링

#180 refactor: 멤버네임 method 변경
  src/main/java/com/sparta/backend/controller/MemberInfoController.java
  src/test/java/com/sparta/backend/serviceImpl/ReminderServiceTest.java
Labels: 🛠 리팩토링

#189 refactor: 리프레시 토큰 관리 수정 및 검색페이지 아티클 검색 추가
  src/main/java/com/sparta/backend/controller/MainPageController.java
  src/main/java/com/sparta/backend/controller/MemberInfoController.java
  src/main/java/com/sparta/backend/controller/OauthController.java
  src/main/java/com/sparta/backend/controller/SearchPageControllerTest.java
  src/main/java/com/sparta/backend/jwt/JwtTokenProvider.java
  src/main/java/com/sparta/backend/repository/ArticleRepository.java
  src/main/java/com/sparta/backend/repository/MemberRepository.java
  src/main/java/com/sparta/backend/repository/RefreshTokenRepository.java
  src/main/java/com/sparta/backend/responseDto/ArticleGetResponseDto.java
  src/main/java/com/sparta/backend/responseDto/MemberLoginResponseDto.java
  src/main/java/com/sparta/backend/security/WebConfig.java
  src/main/java/com/sparta/backend/service/MemberInfoService.java
  src/main/java/com/sparta/backend/service/OauthService.java
  src/main/java/com/sparta/backend/service/SearchPageServiceTest.java
  src/main/java/com/sparta/backend/serviceImpl/MemberInfoServiceImpl.java
  src/main/java/com/sparta/backend/serviceImpl/OauthServiceImpl.java
  src/main/java/com/sparta/backend/serviceImpl/SearchPageServiceTestImpl.java
  src/test/java/com/sparta/backend/nplus1/nplus1test.java
  src/test/java/com/sparta/backend/serviceImpl/MemberInfoServiceTest.java
  src/test/java/com/sparta/backend/serviceImpl/OauthServiceTest.java
  src/test/java/com/sparta/backend/serviceImpl/ReminderServiceTest.java
Labels: 🐞 버그, 🚀 기능추가, 🛠 리팩토링

#190 리팩토링 및 리프레시 토큰 서비스 분리
  src/main/java/com/sparta/backend/controller/MainPageController.java
  src/main/java/com/sparta/backend/controller/MemberInfoController.java
  src/main/java/com/sparta/backend/controller/OauthController.java
  src/main/java/com/sparta/backend/controller/SearchPageControllerTest.java
  src/main/java/com/sparta/backend/jwt/JwtTokenProvider.java
  src/main/java/com/sparta/backend/repository/ArticleRepository.java
  src/main/java/com/sparta/backend/repository/MemberRepository.java
  src/main/java/com/sparta/backend/repository/RefreshTokenRepository.java
  src/main/java/com/sparta/backend/responseDto/ArticleGetResponseDto.java
  src/main/java/com/sparta/backend/responseDto/MemberLoginResponseDto.java
  src/main/java/com/sparta/backend/security/WebConfig.java
  src/main/java/com/sparta/backend/service/MemberInfoService.java
  src/main/java/com/sparta/backend/service/OauthService.java
  src/main/java/com/sparta/backend/service/SearchPageServiceTest.java
  src/main/java/com/sparta/backend/serviceImpl/MemberInfoServiceImpl.java
  src/main/java/com/sparta/backend/serviceImpl/OauthServiceImpl.java
  src/main/java/com/sparta/backend/serviceImpl/SearchPageServiceTestImpl.java
  src/test/java/com/sparta/backend/nplus1/nplus1test.java
  src/test/java/com/sparta/backend/serviceImpl/MemberInfoServiceTest.java
  src/test/java/com/sparta/backend/serviceImpl/OauthServiceTest.java
  src/test/java/com/sparta/backend/serviceImpl/ReminderServiceTest.java
Labels: 🥊 배포
